# Generated by Django 5.1.4 on 2024-12-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('feelslike', models.FloatField()),
                ('dew', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('windgust', models.FloatField()),
                ('winddir', models.FloatField()),
                ('visibility', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.FloatField()),
                ('uvindex', models.IntegerField()),
                ('severerisk', models.IntegerField()),
                ('conditions', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
